locale                   : "en-US"
title                    : "zpic@edu"
title_separator          : "-"
subtitle                 : "PIC codes for plasma physics education"
description              : "Suite of Particle-in-Cell codes for plasma physics education"


#baseurl                  : "/zpic"
repository               : "ricardo-fonseca/zpic"

#remote_theme: pages-themes/cayman
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

atom_feed:
  hide : true

search                   : false
search_full_content      : true

breadcrumbs: true
